// Code generated by "stringer -type=MessageRole,ContentType,ToolChoiceType,StopReason,ThinkingLevel -output=llm_string.go"; DO NOT EDIT.

package llm

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageRoleUser-0]
	_ = x[MessageRoleAssistant-1]
}

const _MessageRole_name = "MessageRoleUserMessageRoleAssistant"

var _MessageRole_index = [...]uint8{0, 15, 35}

func (i MessageRole) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_MessageRole_index)-1 {
		return "MessageRole(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageRole_name[_MessageRole_index[idx]:_MessageRole_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ContentTypeText-2]
	_ = x[ContentTypeThinking-3]
	_ = x[ContentTypeRedactedThinking-4]
	_ = x[ContentTypeToolUse-5]
	_ = x[ContentTypeToolResult-6]
}

const _ContentType_name = "ContentTypeTextContentTypeThinkingContentTypeRedactedThinkingContentTypeToolUseContentTypeToolResult"

var _ContentType_index = [...]uint8{0, 15, 34, 61, 79, 100}

func (i ContentType) String() string {
	idx := int(i) - 2
	if i < 2 || idx >= len(_ContentType_index)-1 {
		return "ContentType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ContentType_name[_ContentType_index[idx]:_ContentType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ToolChoiceTypeAuto-7]
	_ = x[ToolChoiceTypeAny-8]
	_ = x[ToolChoiceTypeNone-9]
	_ = x[ToolChoiceTypeTool-10]
}

const _ToolChoiceType_name = "ToolChoiceTypeAutoToolChoiceTypeAnyToolChoiceTypeNoneToolChoiceTypeTool"

var _ToolChoiceType_index = [...]uint8{0, 18, 35, 53, 71}

func (i ToolChoiceType) String() string {
	idx := int(i) - 7
	if i < 7 || idx >= len(_ToolChoiceType_index)-1 {
		return "ToolChoiceType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ToolChoiceType_name[_ToolChoiceType_index[idx]:_ToolChoiceType_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StopReasonStopSequence-11]
	_ = x[StopReasonMaxTokens-12]
	_ = x[StopReasonEndTurn-13]
	_ = x[StopReasonToolUse-14]
	_ = x[StopReasonRefusal-15]
}

const _StopReason_name = "StopReasonStopSequenceStopReasonMaxTokensStopReasonEndTurnStopReasonToolUseStopReasonRefusal"

var _StopReason_index = [...]uint8{0, 22, 41, 58, 75, 92}

func (i StopReason) String() string {
	idx := int(i) - 11
	if i < 11 || idx >= len(_StopReason_index)-1 {
		return "StopReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StopReason_name[_StopReason_index[idx]:_StopReason_index[idx+1]]
}
func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ThinkingLevelOff-0]
	_ = x[ThinkingLevelMinimal-1]
	_ = x[ThinkingLevelLow-2]
	_ = x[ThinkingLevelMedium-3]
	_ = x[ThinkingLevelHigh-4]
}

const _ThinkingLevel_name = "ThinkingLevelOffThinkingLevelMinimalThinkingLevelLowThinkingLevelMediumThinkingLevelHigh"

var _ThinkingLevel_index = [...]uint8{0, 16, 36, 52, 71, 88}

func (i ThinkingLevel) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_ThinkingLevel_index)-1 {
		return "ThinkingLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ThinkingLevel_name[_ThinkingLevel_index[idx]:_ThinkingLevel_index[idx+1]]
}
